### ISSUE TITLE
ActiveSupport::EncryptedFile::MissingKeyError when building image

### ISSUE THREAD

**Issue by Quintasan** [ledermann/docker-rails-base#111]
```
# Dockerfile
FROM ledermann/rails-base-builder:latest AS builder

FROM nginx:alpine
COPY --from=builder /app/public /usr/share/nginx/html/
```

```
# build.log 
Step 1/5 : FROM ledermann/rails-base-builder:latest AS builder
# Executing 5 build triggers
 ---> Using cache
 ---> Using cache
 ---> Running in e572cd7508c3
rails aborted!
ActiveSupport::EncryptedFile::MissingKeyError: Missing encryption key to decrypt file with. Ask your team for your master key and write it to /app/config/master.key or put it in the ENV['RAILS_MASTER_KEY'].
```

I tried to use

```
# Dockerfile
FROM ledermann/rails-base-builder:latest AS builder
ARG CREDENTIALS_KEY=changeme
ENV RAILS_MASTER_KEY=$CREDENTIALS_KEY

FROM nginx:alpine
COPY --from=builder /app/public /usr/share/nginx/html/
```

to allow usage with `docker-compose --build-arg` but it doesn't work that way :(

Any suggested solution?

**Comment by ledermann** [comment]
It seems you have `config.require_master_key = true` in your `production.rb` file. Because the assets are compiled in `production` env, Rails requires the master key for building assets and raises a `MissingKeyError` if it's missing.

I don't think that the master key should be present while building the Docker image, which mostly is done on a CI server. I've just commited a fix for this, does it help in your case?

**Comment by Quintasan** [comment]
@ledermann Your fix did work but I'm not running into gem issues for some reason. Want me to open another issue?

**Comment by ledermann** [comment]
Sure, feel free to open another issue.
