### ISSUE TITLE
how to add package like sqlite-dev

### ISSUE THREAD

**Issue by zhangpy** [ledermann/docker-rails-base#1277]
I tried this way
```
FROM ledermann/rails-base-builder:3.1.1-alpine AS Builder
FROM ledermann/rails-base-final:3.1.1-alpine

RUN apk add --no-cache sqlite-dev
USER app
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
```
failed with cmd docker build .
```
Installing sqlite3 1.4.2 with native extensions
Installing importmap-rails 1.0.3
Installing stimulus-rails 1.0.4
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/bundle/gems/sqlite3-1.4.2/ext/sqlite3
/usr/local/bin/ruby -I /usr/local/lib/ruby/3.1.0 -r
./siteconf20220313-8-4cuwka.rb extconf.rb
checking for sqlite3.h... no
sqlite3.h is missing. Try 'brew install sqlite3',
'yum install sqlite-devel' or 'apt-get install libsqlite3-dev'
```
it seems sqlite-dev is not added before onbuild is triggered.
maybe I need build my builder image?

**Comment by ledermann** [comment]
Yes, you are right, the `sqlite-dev` package is required for installing the `sqlite3` gem - and this cannot be customized in the projects Dockerfile. Maybe I should find a way to do this.

To fix the issue for now, I have added the package `sqlite-dev` (and `mariadb-dev` because for MySQL/MariaDB there is the same problem) to the `Builder` image.
