### ISSUE TITLE
how to add alpine packages in Build Stage

### ISSUE THREAD

**Issue by itsyoshio** [ledermann/docker-rails-base#2113]
I (sadly) have the need for imagemagick(-dev, -libs) in my Build Stage in Order to use a certain gem later in Production.

How would that be possible?
I tried copying the whole [Builder Dockerfile](https://github.com/ledermann/docker-rails-base/blob/main/Builder/Dockerfile) in place of `FROM ledermann/rails-base-builder:3.2.2-alpine AS Builder` but i don't get running Images.

Appreciated!

**Comment by ledermann** [comment]
Since most of the speed benefit comes from the precompiled Docker image, the `Builder` image would need to be extended with the Imagemagick stuff. It's not possible to add build-time packages in your app's Dockerfile.

The `Builder` image currently includes the following Alpine packages, which is sufficient for my personal needs (= the Rails apps I'm currently working on):

```
- build-base 
- gcompat 
- vips-dev 
- postgresql-dev 
- sqlite-dev 
- mariadb-dev 
- git 
- nodejs 
- npm 
- yarn 
- tzdata 
- file
```

This results in a Docker image size of **1.43 GB**, which is already quite a lot. I am therefore hesitant to add more packages. Of course, you can fork the project and add packages according to your needs.

BUT: I just tested the increase of adding the `imagemagick-dev` package. Because it's less than I thought (+ 100 MB), I have added it :-)

Hope this helps.

**Comment by itsyoshio** [comment]
This is wonderful, thank you so much. 🥰
