### ISSUE TITLE
Plans to add tagging?

### ISSUE THREAD

**Issue by deepakinseattle** [ledermann/docker-rails-base#439]
Hello, Georg. Thanks for putting together the builder and the final docker images. I've recently started using this instead of rolling my own, and the images they produce are nice and lean.

Do you have any plans to add tags to the docker images you push? I had CI start failing on me today because I'm still using Ruby 2.7.1. 

With the update of this image to 2.7.2, my docker build step began to fail in CI with `Your Ruby version is 2.7.2, but your Gemfile specified 2.7.1` since my Gemfile.lock still has 2.7.1. 

Tagging these images (perhaps consistent with the base ruby tag e.g. `2.7.2-alpine`) would be a welcome way to avoid getting caught by surprise.

I'm happy to help with a PR if you've got a direction in mind for how you'd like to see the tagging implemented.

**Comment by ledermann** [comment]
Hello Deepak, thank you for describing this, you are absolutely right. I just fixed this so that images are now tagged with the name of the base image tag. I have rebuilt the images for 2.7.1, so at this moment these tags are available:

* 2.7.1-alpine
* 2.7.2-alpine

You can fix your app without updating to 2.7.2 by changing your Dockerfile to this:

```Dockerfile
FROM ledermann/rails-base-builder:2.7.1-alpine as Builder
FROM ledermann/rails-base-final:2.7.1-alpine
...
```

Note that the 2.7.1 image will not be updated in the future.
