### ISSUE TITLE
Have problem when run on AWS ECS after updated to 3.0.2-alpine

### ISSUE THREAD

**Issue by cpanuphan** [ledermann/docker-rails-base#881]
After I updated ledermann/rails-base-builder:3.0.2-alpine and ledermann/rails-base-final:3.0.2-alpine.
I met the problem when running my image on AWS ECS with errors **`/home/app` is not writable** even I set USER to app on Dockerfile.
[Full errors](https://imgur.com/eCQlDB7).

Do you have any suggestions?

**Comment by ledermann** [comment]
This may not be due to Ruby 3.0.2, but to the upgrade to Alpine 3.14 made by the Ruby Docker Project [two weeks ago](https://github.com/docker-library/ruby/commit/0c5948bcce84b1829a554209c777f0ef6a357dd2).

Alpine 3.14 has some new requirements, e.g. it requires Docker 20.10.0 or later:
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0

There is a discussion about this here:
https://github.com/docker-library/ruby/issues/351

**Comment by cpanuphan** [comment]
Thank you for your help.
Yes the version on AWS EC2 is 19.03.13-ce.
